### PR TITLE
Support gettext message

### PR DESCRIPTION
**Pull request by mrdotb**
Hello, we are using your library and need to translate the dynamic error message with gettext.
I modify the code a bit but it's not finish yet.
I saw a related thread #15.
Are you interested to merge those changes when it's finish ?

Thanks

### CODE REVIEW

**Comment by mrdotb** [comment]
So I finished the modifications.
The difference now for the calls with dynamics errors.
```elixir
PasswordValidator.validate_password("too_long", opts)
# will return
# {:error, [{"String is too long. %{length} but maximum is %{max}", length: 8, max: 6}]}
# instead of
# {:error, ["String is too long. 8 but maximum is 6"]}
```
Unfortunately, It's breaking change.

Anyway I extracted all the strings to translate from password-validator and elixir-zxcvbn if it can be usefull.
https://gist.github.com/mrdotb/085492f99e3a77f547b0971e66f6f9a8

**Comment by axelson** [comment]
Hi :wave:!

Thanks for the PR! I have some initial thoughts:
1. Allowing for the translation of error messages via gettext is good feature to have
1. I already have some code locally for #15 that I would like to get in first (unless it ends up being significantly easier to get this PR in first), but either way I want to finalize the required API changes before merging this PR
1. I want to investigate making `:gettext` an optional dependency and changing the behavior based on if `:gettext` is included in the end user's project (I put up a related Elixir forum post on this: https://elixirforum.com/t/is-there-a-guide-for-relying-on-optional-dependencies-in-a-library/37318)
1. Since this is a breaking change we will need a migration guide as well as a guide on how to use this library with the end user's `MyApp.Gettext` module
1. In PasswordValidator we should add functionality to convert `{:error, [{"String is too long. %{length} but maximum is %{max}", length: 8, max: 6}]}` to `{:error, ["String is too long. 8 but maximum is 6"]}`
   - Note: this might only be required if we don't have full support for optional dependencies
1. I would like to see the contents of https://gist.github.com/mrdotb/085492f99e3a77f547b0971e66f6f9a8 included in the git repo and ideally tested to ensure that the messages stay up to date

Whew, that ended up being quite the list :sweat_smile:

**Comment by mrdotb** [comment]
:wave:

2. I think it will be easier to add #15 first since I have to modify the part with the `Changeset.add_error/4`

3. I added this small fn to fix the tests we could move it to the lib and use it if Gettext is here or not.
```elixir
  def errors_on(errors) when is_list(errors) do
    Enum.map(errors, fn
      {message, keys} ->
        Regex.replace(~r"%{(\w+)}", message, fn _, key ->
          keys |> Keyword.get(String.to_existing_atom(key), key) |> to_string()
        end)

      error ->
        error
    end)
  end
```
4. It should work out of the box with the default phoenix `Helpers.Error` who looks like this. But we can add some docs for the one using something more custom.
```elixir
  def error_tag(form, field) do
    Enum.map(Keyword.get_values(form.errors, field), fn error ->
      content_tag(:span, translate_error(error),
        class: "invalid-feedback",
        phx_feedback_for: input_id(form, field)
      )
    end)
  end

  def translate_error({msg, opts}) do
    if count = opts[:count] do
      Gettext.dngettext(AppWeb.Gettext, "errors", msg, msg, count, opts)
    else
      Gettext.dgettext(AppWeb.Gettext, "errors", msg, opts)
    end
  end
  ```
6. Yes it would be nice to find the po files of password-validator and zxcvbn-elixir (extracting them is a bit annoying)
I can also provide the :fr:  translations we did.

:turtle:  It can take time we fixed our problems using my forked version. 

I will come back to check how I can help when you are done with the API changes

**Comment by axelson** [comment]
@mrdotb just put up #17 if you want to take a look. I'll probably merge it later today after I've gotten all the ci bugs out of the way. The good news is that I didn't need to make any large API changes.

**Comment by mrdotb** [comment]
I need to open another MR I need to keep my master fork since the project is using it and I can not update the branch on this PR.

**Pull request closed without merging**
